### ISSUE TITLE
Add documentation for in-app config

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#248]
Self-explanatory.

## Todo:

- [ ] https://github.com/ClementTsang/bottom/pull/257 - Update documentation for: 
  - [ ] `case_sensitive`
  - [ ] `whole_word`
  - [ ] `regex` 
  for config and flags, and
  - [ ] `flags.search_case_enabled_widgets`
  - [ ] `flags.search_whole_word_enabled_widgets`
  - [ ] `flags.search_regex_enabled_widgets`
  which are new.
